name: '✔️ PR Checks'
on:
  pull_request:
    branches:
      - 'main'

jobs:
  code-quality:
    name: '💎 Code-Quality'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dev dependencies
        run: pip install -e ".[dev]"

      - name: Lint checks with ruff
        run: ruff check app

      - name: Typing checks with mypy
        run: mypy app --pretty

      - name: Formatting checks with black
        run: black --check app
